name: Build and Deploy to 'build' branch

on:
    push:
        branches: [production]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Deploy to 'build' branch
              run: |
                  # Preparar git para hacer push a otro branch
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'

                  # Crear un directorio temporal con el contenido de dist/
                  mkdir ../build-dir

                  # Clonar el branch build
                  git clone --branch build https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ../build-dir

                  cd ../build-dir

                  # Borrar todo (excepto .git)
                  find . -maxdepth 1 ! -name .git ! -name . -exec rm -rf {} +

                  # Copiar el nuevo build
                  cp -r ../dist/* .

                  # Commit y push si hay cambios
                  git add .
                  git commit -m "Deploy build from ${{ github.sha }}" || echo "No changes to commit"
                  git push origin build
